name: Pull Request Trigger

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run tests
      run: |
        # Add your test commands here
        
    - name: Deploy
      uses: some-action-for-deployment@v1
      with:
        # Add your deployment configuration here